export const britBirds = {
        bahgoo:"Bar-headed Goose",
        empgoo:"Emperor Goose",
        snogoo:"Snow Goose",
        rosgoo:"Ross's Goose",
        gragoo:"Graylag Goose",
        swagoo1:"Swan Goose",
        gwfgoo:"Greater White-fronted Goose",
        lwfgoo:"Lesser White-fronted Goose",
        taibeg1:"Taiga Bean-Goose",
        tunbeg1:"Tundra Bean-Goose",
        pifgoo:"Pink-footed Goose",
        brant:"Brant",
        bargoo:"Barnacle Goose",
        cacgoo1:"Cackling Goose",
        cangoo:"Canada Goose",
        hawgoo:"Hawaiian Goose",
        rebgoo1:"Red-breasted Goose",
        mutswa:"Mute Swan",
        blkswa:"Black Swan",
        truswa:"Trumpeter Swan",
        tunswa:"Tundra Swan",
        whoswa:"Whooper Swan",
        egygoo:"Egyptian Goose",
        rudshe:"Ruddy Shelduck",
        soashe1:"South African Shelduck",
        comshe:"Common Shelduck",
        creduc1:"Crested Duck",
        musduc:"Muscovy Duck",
        rintea1:"Ringed Teal",
        wooduc:"Wood Duck",
        manduc:"Mandarin Duck",
        baitea:"Baikal Teal",
        gargan:"Garganey",
        buwtea:"Blue-winged Teal",
        cintea:"Cinnamon Teal",
        norsho:"Northern Shoveler",
        gadwal:"Gadwall",
        falduc:"Falcated Duck",
        eurwig:"Eurasian Wigeon",
        amewig:"American Wigeon",
        chiwig1:"Chiloe Wigeon",
        mallar3:"Mallard",
        ambduc:"American Black Duck",
        captea1:"Cape Teal",
        whcpin:"White-cheeked Pintail",
        norpin:"Northern Pintail",
        yebpin1:"Yellow-billed Pintail",
        gnwtea:"Green-winged Teal",
        yebtea1:"Yellow-billed Teal",
        martea1:"Marbled Teal",
        recpoc:"Red-crested Pochard",
        robpoc1:"Rosy-billed Pochard",
        canvas:"Canvasback",
        redhea:"Redhead",
        compoc:"Common Pochard",
        rinduc:"Ring-necked Duck",
        ferduc:"Ferruginous Duck",
        tufduc:"Tufted Duck",
        gresca:"Greater Scaup",
        lessca:"Lesser Scaup",
        steeid:"Steller's Eider",
        kineid:"King Eider",
        comeid:"Common Eider",
        harduc:"Harlequin Duck",
        sursco:"Surf Scoter",
        whwsco3:"Velvet Scoter",
        whwsco2:"White-winged Scoter",
        whwsco1:"Stejneger's Scoter",
        blksco1:"Common Scoter",
        blksco2:"Black Scoter",
        lotduc:"Long-tailed Duck",
        buffle:"Bufflehead",
        comgol:"Common Goldeneye",
        bargol:"Barrow's Goldeneye",
        smew:"Smew",
        hoomer:"Hooded Merganser",
        commer:"Common Merganser",
        rebmer:"Red-breasted Merganser",
        rudduc:"Ruddy Duck",
        whhduc1:"White-headed Duck",
        helgui:"Helmeted Guineafowl",
        norbob:"Northern Bobwhite",
        wilpta:"Willow Ptarmigan",
        rocpta1:"Rock Ptarmigan",
        wescap1:"Western Capercaillie",
        blagro1:"Black Grouse",
        grypar:"Gray Partridge",
        reephe1:"Reeves's Pheasant",
        golphe:"Golden Pheasant",
        laaphe1:"Lady Amherst's Pheasant",
        rinphe:"Ring-necked Pheasant",
        kalphe:"Kalij Pheasant",
        silphe:"Silver Pheasant",
        compea:"Indian Peafowl",
        comqua1:"Common Quail",
        relpar1:"Red-legged Partridge",
        chukar:"Chukar",
        chifla1:"Chilean Flamingo",
        grefla3:"Greater Flamingo",
        lesfla1:"Lesser Flamingo",
        litgre1:"Little Grebe",
        pibgre:"Pied-billed Grebe",
        horgre:"Horned Grebe",
        rengre:"Red-necked Grebe",
        grcgre1:"Great Crested Grebe",
        eargre:"Eared Grebe",
        rocpig:"Rock Pigeon",
        stodov1:"Stock Dove",
        cowpig1:"Common Wood-Pigeon",
        eutdov:"European Turtle-Dove",
        ortdov:"Oriental Turtle-Dove",
        eucdov:"Eurasian Collared-Dove",
        moudov:"Mourning Dove",
        palsan1:"Pallas's Sandgrouse",
        grebus1:"Great Bustard",
        litbus1:"Little Bustard",
        grscuc1:"Great Spotted Cuckoo",
        yebcuc:"Yellow-billed Cuckoo",
        bkbcuc:"Black-billed Cuckoo",
        comcuc:"Common Cuckoo",
        comnig:"Common Nighthawk",
        eurnig1:"Eurasian Nightjar",
        egynig1:"Egyptian Nightjar",
        chiswi:"Chimney Swift",
        whtnee:"White-throated Needletail",
        alpswi1:"Alpine Swift",
        comswi:"Common Swift",
        palswi3:"Pallid Swift",
        fotswi:"Pacific Swift",
        litswi1:"Little Swift",
        whrswi1:"White-rumped Swift",
        watrai1:"Water Rail",
        corcra:"Corn Crake",
        sora:"Sora",
        spocra1:"Spotted Crake",
        commoo3:"Eurasian Moorhen",
        eurcoo:"Eurasian Coot",
        y00475:"American Coot",
        purgal2:"Purple Gallinule",
        purswa1:"Western Swamphen",
        litcra1:"Little Crake",
        baicra1:"Baillon's Crake",
        sancra:"Sandhill Crane",
        comcra:"Common Crane",
        eutkne1:"Eurasian Thick-knee",
        bkwsti:"Black-winged Stilt",
        pieavo1:"Pied Avocet",
        euroys1:"Eurasian Oystercatcher",
        bkbplo:"Black-bellied Plover",
        eugplo:"European Golden-Plover",
        amgplo:"American Golden-Plover",
        pagplo:"Pacific Golden-Plover",
        norlap:"Northern Lapwing",
        spwlap1:"Spur-winged Lapwing",
        soclap1:"Sociable Lapwing",
        whtlap1:"White-tailed Lapwing",
        lesplo:"Lesser Sand-Plover",
        grsplo:"Greater Sand-Plover",
        casplo1:"Caspian Plover",
        kenplo1:"Kentish Plover",
        corplo:"Common Ringed Plover",
        semplo:"Semipalmated Plover",
        lirplo:"Little Ringed Plover",
        killde:"Killdeer",
        eurdot:"Eurasian Dotterel",
        uplsan:"Upland Sandpiper",
        whimbr:"Whimbrel",
        litcur:"Little Curlew",
        eskcur:"Eskimo Curlew",
        eurcur:"Eurasian Curlew",
        batgod:"Bar-tailed Godwit",
        bktgod:"Black-tailed Godwit",
        hudgod:"Hudsonian Godwit",
        rudtur:"Ruddy Turnstone",
        grekno:"Great Knot",
        redkno:"Red Knot",
        ruff:"Ruff",
        brbsan:"Broad-billed Sandpiper",
        shtsan:"Sharp-tailed Sandpiper",
        stisan:"Stilt Sandpiper",
        cursan:"Curlew Sandpiper",
        temsti:"Temminck's Stint",
        lotsti:"Long-toed Stint",
        rensti:"Red-necked Stint",
        sander:"Sanderling",
        dunlin:"Dunlin",
        pursan:"Purple Sandpiper",
        baisan:"Baird's Sandpiper",
        litsti:"Little Stint",
        leasan:"Least Sandpiper",
        whrsan:"White-rumped Sandpiper",
        bubsan:"Buff-breasted Sandpiper",
        pecsan:"Pectoral Sandpiper",
        semsan:"Semipalmated Sandpiper",
        wessan:"Western Sandpiper",
        shbdow:"Short-billed Dowitcher",
        lobdow:"Long-billed Dowitcher",
        jacsni:"Jack Snipe",
        eurwoo:"Eurasian Woodcock",
        gresni1:"Great Snipe",
        comsni:"Common Snipe",
        wilsni1:"Wilson's Snipe",
        tersan:"Terek Sandpiper",
        wilpha:"Wilson's Phalarope",
        renpha:"Red-necked Phalarope",
        redpha1:"Red Phalarope",
        comsan:"Common Sandpiper",
        sposan:"Spotted Sandpiper",
        grnsan:"Green Sandpiper",
        solsan:"Solitary Sandpiper",
        gyttat1:"Gray-tailed Tattler",
        spored:"Spotted Redshank",
        greyel:"Greater Yellowlegs",
        comgre:"Common Greenshank",
        lesyel:"Lesser Yellowlegs",
        marsan:"Marsh Sandpiper",
        woosan:"Wood Sandpiper",
        comred1:"Common Redshank",
        crccou1:"Cream-colored Courser",
        colpra:"Collared Pratincole",
        oripra:"Oriental Pratincole",
        blwpra1:"Black-winged Pratincole",
        gresku1:"Great Skua",
        sopsku1:"South Polar Skua",
        pomjae:"Pomarine Jaeger",
        parjae:"Parasitic Jaeger",
        lotjae:"Long-tailed Jaeger",
        doveki:"Dovekie",
        commur:"Common Murre",
        thbmur:"Thick-billed Murre",
        razorb:"Razorbill",
        blkgui:"Black Guillemot",
        lobmur:"Long-billed Murrelet",
        ancmur:"Ancient Murrelet",
        atlpuf:"Atlantic Puffin",
        tufpuf:"Tufted Puffin",
        bklkit:"Black-legged Kittiwake",
        ivogul:"Ivory Gull",
        sabgul:"Sabine's Gull",
        slbgul1:"Slender-billed Gull",
        bongul:"Bonaparte's Gull",
        bkhgul:"Black-headed Gull",
        litgul:"Little Gull",
        rosgul:"Ross's Gull",
        laugul:"Laughing Gull",
        fragul:"Franklin's Gull",
        medgul1:"Mediterranean Gull",
        audgul1:"Audouin's Gull",
        mewgul:"Common Gull",
        ribgul:"Ring-billed Gull",
        hergul:"Herring Gull",
        yelgul1:"Yellow-legged Gull",
        casgul2:"Caspian Gull",
        y00478:"Iceland Gull",
        lbbgul:"Lesser Black-backed Gull",
        slbgul:"Slaty-backed Gull",
        glwgul:"Glaucous-winged Gull",
        glagul:"Glaucous Gull",
        gbbgul:"Great Black-backed Gull",
        sooter1:"Sooty Tern",
        briter1:"Bridled Tern",
        litter1:"Little Tern",
        leater1:"Least Tern",
        gubter1:"Gull-billed Tern",
        caster1:"Caspian Tern",
        blkter:"Black Tern",
        whwter:"White-winged Tern",
        whiter2:"Whiskered Tern",
        roster:"Roseate Tern",
        comter:"Common Tern",
        arcter:"Arctic Tern",
        forter:"Forster's Tern",
        royter1:"Royal Tern",
        santer1:"Sandwich Tern",
        eleter1:"Elegant Tern",
        lecter2:"Lesser Crested Tern",
        royter2:"West African Crested Tern",
        rebtro:"Red-billed Tropicbird",
        retloo:"Red-throated Loon",
        arcloo:"Arctic Loon",
        pacloo:"Pacific Loon",
        comloo:"Common Loon",
        yebloo:"Yellow-billed Loon",
        bkbalb:"Black-browed Albatross",
        wispet:"Wilson's Storm-Petrel",
        bripet:"European Storm-Petrel",
        lcspet:"Leach's Storm-Petrel",
        swspet:"Swinhoe's Storm-Petrel",
        barpet:"Band-rumped Storm-Petrel",
        norful:"Northern Fulmar",
        feapet1:"Fea's Petrel",
        soppet1:"Soft-plumaged Petrel",
        corshe:"Cory's Shearwater",
        greshe:"Great Shearwater",
        sooshe:"Sooty Shearwater",
        manshe:"Manx Shearwater",
        levshe1:"Yelkouan Shearwater",
        balshe1:"Balearic Shearwater",   
        litshe1:"Barolo Shearwater",
        blasto1:"Black Stork",
        whisto1:"White Stork",
        brnboo:"Brown Booby",
        norgan:"Northern Gannet",
        grecor:"Great Cormorant",
        eursha1:"European Shag",
        doccor:"Double-crested Cormorant",
        grwpel1:"Great White Pelican",
        dalpel1:"Dalmatian Pelican",
        amebit:"American Bittern",
        grebit1:"Great Bittern",
        litbit1:"Little Bittern",
        grbher3:"Great Blue Heron",
        graher1:"Gray Heron",
        purher1:"Purple Heron",
        greegr:"Great Egret",
        litegr:"Little Egret",
        snoegr:"Snowy Egret",
        categr:"Cattle Egret",
        squher1:"Squacco Heron",
        chpher1:"Chinese Pond-Heron",
        grnher:"Green Heron",
        bcnher:"Black-crowned Night-Heron",
        gloibi:"Glossy Ibis",
        sacibi2:"African Sacred Ibis",
        waldra1:"Northern Bald Ibis",
        eurspo1:"Eurasian Spoonbill",
        osprey:"Osprey",
        lammer1:"Bearded Vulture",
        egyvul1:"Egyptian Vulture",
        euhbuz1:"European Honey-buzzard",
        shteag1:"Short-toed Snake-Eagle",
        booeag1:"Booted Eagle",
        goleag:"Golden Eagle",
        wemhar1:"Eurasian Marsh-Harrier",
        norhar1:"Hen Harrier",
        norhar2:"Northern Harrier",
        palhar1:"Pallid Harrier",
        monhar1:"Montagu's Harrier",
        eurspa1:"Eurasian Sparrowhawk",
        norgos:"Northern Goshawk",
        redkit1:"Red Kite",
        blakit1:"Black Kite",
        whteag:"White-tailed Eagle",
        hrshaw:"Harris's Hawk",
        rethaw:"Red-tailed Hawk",
        rolhaw:"Rough-legged Hawk",
        combuz1:"Common Buzzard",
        brnowl:"Barn Owl",
        eursco1:"Eurasian Scops-Owl",
        eueowl1:"Eurasian Eagle-Owl",
        snoowl1:"Snowy Owl",
        nohowl:"Northern Hawk Owl",
        litowl1:"Little Owl",
        tawowl1:"Tawny Owl",
        loeowl:"Long-eared Owl",
        sheowl:"Short-eared Owl",
        borowl:"Boreal Owl",
        hoopoe:"Eurasian Hoopoe",
        comkin1:"Common Kingfisher",
        belkin1:"Belted Kingfisher",
        bcbeat1:"Blue-cheeked Bee-eater",
        eubeat1:"European Bee-eater",
        eurrol1:"European Roller",
        eurwry:"Eurasian Wryneck",
        grswoo:"Great Spotted Woodpecker",
        leswoo1:"Lesser Spotted Woodpecker",
        eugwoo2:"Eurasian Green Woodpecker",
        leskes1:"Lesser Kestrel",
        eurkes:"Eurasian Kestrel",
        amekes:"American Kestrel",
        reffal1:"Red-footed Falcon",
        amufal1:"Amur Falcon",
        elefal1:"Eleonora's Falcon",
        merlin:"Merlin",
        eurhob:"Eurasian Hobby",
        sakfal1:"Saker Falcon",
        gyrfal:"Gyrfalcon",
        perfal:"Peregrine Falcon",
        cockat:"Cockatiel",
        alepar2:"Alexandrine Parakeet",
        rorpar:"Rose-ringed Parakeet",
        derpar1:"Derbyan Parakeet",
        monpar:"Monk Parakeet",
        burpar:"Burrowing Parakeet",
        yebfly:"Yellow-bellied Flycatcher",
        acafly:"Acadian Flycatcher",
        aldfly:"Alder Flycatcher",
        easkin:"Eastern Kingbird",
        yetvir:"Yellow-throated Vireo",
        phivir:"Philadelphia Vireo",
        reevir1:"Red-eyed Vireo",
        eugori2:"Eurasian Golden Oriole",
        rebshr1:"Red-backed Shrike",
        rutshr2:"Red-tailed Shrike",
        isashr1:"Isabelline Shrike",
        brnshr:"Brown Shrike",
        lotshr1:"Long-tailed Shrike",
        norshr1:"Great Gray Shrike",
        legshr2:"Lesser Gray Shrike",
        masshr1:"Masked Shrike",
        wooshr1:"Woodchat Shrike",
        eurjay1:"Eurasian Jay",
        eurmag1:"Eurasian Magpie",
        eurnut1:"Eurasian Nutcracker",
        rebcho1:"Red-billed Chough",
        eurjac:"Eurasian Jackdaw",
        rook1:"Rook",
        carcro1:"Carrion Crow",
        hoocro1:"Hooded Crow",
        comrav:"Common Raven",
        coatit2:"Coal Tit",
        cretit2:"Crested Tit",
        martit2:"Marsh Tit",
        wiltit1:"Willow Tit",
        blutit:"Eurasian Blue Tit",
        gretit1:"Great Tit",
        euptit1:"Eurasian Penduline-Tit",
        horlar:"Horned Lark",
        gstlar1:"Greater Short-toed Lark",
        bimlar1:"Bimaculated Lark",
        callar1:"Calandra Lark",
        blalar1:"Black Lark",
        woolar1:"Wood Lark",
        skylar:"Eurasian Skylark",
        crelar2:"Crested Lark",
        bearee1:"Bearded Reedling",
        zitcis1:"Zitting Cisticola",
        thbwar1:"Thick-billed Warbler",
        boowar1:"Booted Warbler",
        sykwar2:"Sykes's Warbler",
        eaowar1:"Eastern Olivaceous Warbler",
        weowar1:"Western Olivaceous Warbler",
        melwar1:"Melodious Warbler",
        ictwar1:"Icterine Warbler",
        aquwar1:"Aquatic Warbler",
        sedwar1:"Sedge Warbler",
        padwar1:"Paddyfield Warbler",
        blrwar1:"Blyth's Reed Warbler",
        marwar3:"Marsh Warbler",
        eurwar1:"Eurasian Reed Warbler",
        grrwar1:"Great Reed Warbler",
        pagwar1:"Pallas's Grasshopper Warbler",
        lanwar:"Lanceolated Warbler",
        eurwar2:"River Warbler",
        savwar1:"Savi's Warbler",
        cogwar1:"Common Grasshopper-Warbler",
        purmar:"Purple Martin",
        treswa:"Tree Swallow",
        banswa:"Bank Swallow",
        eurcrm1:"Eurasian Crag-Martin",
        barswa:"Barn Swallow",
        rerswa1:"Red-rumped Swallow",
        cliswa:"Cliff Swallow",
        cohmar1:"Common House-Martin",
        woowar:"Wood Warbler",
        webwar1:"Western Bonelli's Warbler",
        eabwar1:"Eastern Bonelli's Warbler",
        yebwar3:"Yellow-browed Warbler",
        humwar1:"Hume's Warbler",
        palwar5:"Pallas's Leaf Warbler",
        radwar1:"Radde's Warbler",
        subwar2:"Sulphur-bellied Warbler",
        duswar:"Dusky Warbler",
        wlwwar:"Willow Warbler",
        comchi1:"Common Chiffchaff",
        ibechi2:"Iberian Chiffchaff",
        eacwar1:"Eastern Crowned Warbler",
        grnwar1:"Green Warbler",
        grewar3:"Greenish Warbler",
        grewar2:"Two-barred Warbler",
        arcwar1:"Arctic Warbler",
        cetwar1:"Cetti's Warbler",
        lottit1:"Long-tailed Tit",
        blackc1:"Eurasian Blackcap",
        garwar1:"Garden Warbler",
        barwar1:"Barred Warbler",
        leswhi4:"Lesser Whitethroat",
        weowar2:"Western Orphean Warbler",
        eaowar2:"Eastern Orphean Warbler",
        asdwar1:"Asian Desert Warbler",
        ruewar1:"Rüppell's Warbler",
        sarwar1:"Sardinian Warbler",
        subwar8:"Moltoni's Warbler",
        subwar6:"Western Subalpine Warbler",
        easwar1:"Eastern Subalpine Warbler",
        grewhi1:"Greater Whitethroat",
        spewar2:"Spectacled Warbler",
        marwar1:"Marmora's Warbler",
        darwar1:"Dartford Warbler",
        indwhe1:"Indian White-eye",
        goldcr1:"Goldcrest",
        firecr1:"Common Firecrest",
        wallcr1:"Wallcreeper",
        eurnut2:"Eurasian Nuthatch",
        rebnut:"Red-breasted Nuthatch",
        eurtre1:"Eurasian Treecreeper",
        shttre1:"Short-toed Treecreeper",
        winwre4:"Eurasian Wren",
        whtdip1:"White-throated Dipper",
        eursta:"European Starling",
        rossta2:"Rosy Starling",
        dausta1:"Daurian Starling",
        commyn:"Common Myna",
        grycat:"Gray Catbird",
        normoc:"Northern Mockingbird",
        scathr2:"White's Thrush",
        varthr:"Varied Thrush",
        veery:"Veery",
        gycthr:"Gray-cheeked Thrush",
        swathr:"Swainson's Thrush",
        herthr:"Hermit Thrush",
        woothr:"Wood Thrush",
        sibthr1:"Siberian Thrush",
        misthr1:"Mistle Thrush",
        sonthr1:"Song Thrush",
        redwin:"Redwing",
        eurbla:"Eurasian Blackbird",
        amerob:"American Robin",
        eyethr:"Eyebrowed Thrush",
        fieldf:"Fieldfare",
        rinouz1:"Ring Ouzel",
        datthr1:"Black-throated Thrush",
        retthr1:"Red-throated Thrush",
        dusthr2:"Dusky Thrush",
        dusthr1:"Naumann's Thrush",
        asbfly:"Asian Brown Flycatcher",
        spofly1:"Spotted Flycatcher",
        rutscr1:"Rufous-tailed Scrub-Robin",
        eurrob1:"European Robin",
        rutrob1:"Rufous-tailed Robin",
        sibrob:"Siberian Blue Robin",
        whtrob3:"White-throated Robin",
        thrnig1:"Thrush Nightingale",
        comnig1:"Common Nightingale",
        blueth:"Bluethroat",
        sibrub:"Siberian Rubythroat",
        refblu:"Red-flanked Bluetail",
        mugfly:"Mugimaki Flycatcher",
        taifly1:"Taiga Flycatcher",
        rebfly:"Red-breasted Flycatcher",
        eupfly1:"European Pied Flycatcher",
        colfly1:"Collared Flycatcher",
        comred2:"Common Redstart",
        blared1:"Black Redstart",
        rtrthr1:"Rufous-tailed Rock-Thrush",
        burthr:"Blue Rock-Thrush",
        whinch1:"Whinchat",
        stonec4:"European Stonechat",
        sibsto1:"Siberian Stonechat",
        stonec7:"Amur Stonechat",
        norwhe:"Northern Wheatear",
        isawhe1:"Isabelline Wheatear",
        deswhe1:"Desert Wheatear",
        bkewhe1:"Western Black-eared Wheatear",
        bkewhe2:"Eastern Black-eared Wheatear",
        piewhe1:"Pied Wheatear",
        whtwhe1:"White-crowned Wheatear",
        bohwax:"Bohemian Waxwing",
        cedwax:"Cedar Waxwing",
        alpacc1:"Alpine Accentor",
        sibacc:"Siberian Accentor",
        dunnoc1:"Dunnock",
        houspa:"House Sparrow",
        spaspa1:"Spanish Sparrow",
        eutspa:"Eurasian Tree Sparrow",
        rocpet1:"Rock Sparrow",
        grywag:"Gray Wagtail",
        eaywag1:"Western Yellow Wagtail",
        eaywag:"Eastern Yellow Wagtail",
        citwag:"Citrine Wagtail",
        whiwag:"White Wagtail",
        ricpip1:"Richard's Pipit",
        oripip1:"Paddyfield Pipit",
        blypip1:"Blyth's Pipit",
        tawpip1:"Tawny Pipit",
        meapip1:"Meadow Pipit",
        trepip:"Tree Pipit",
        olbpip:"Olive-backed Pipit",
        pecpip:"Pechora Pipit",
        retpip:"Red-throated Pipit",
        watpip1:"Water Pipit",
        rocpip1:"Rock Pipit",
        amepip:"American Pipit",
        comcha:"Common Chaffinch",
        brambl:"Brambling",
        hawfin:"Hawfinch",
        comros:"Common Rosefinch",
        pingro:"Pine Grosbeak",
        eurbul:"Eurasian Bullfinch",
        trufin2:"Trumpeter Finch",
        houfin:"House Finch",
        desfin2:"Desert Finch",
        eurgre1:"European Greenfinch",
        twite1:"Twite",
        eurlin1:"Eurasian Linnet",
        comred:"Common Redpoll",
        lesred1:"Lesser Redpoll",
        hoared:"Hoary Redpoll",
        parcro2:"Parrot Crossbill",
        scocro1:"Scottish Crossbill",
        redcro:"Red Crossbill",
        whwcro:"White-winged Crossbill",
        eurgol:"European Goldfinch",
        citfin1:"Citril Finch",
        eurser1:"European Serin",
        eursis:"Eurasian Siskin",
        laplon:"Lapland Longspur",
        snobun:"Snow Bunting",
        blhbun1:"Black-headed Bunting",
        rehbun1:"Red-headed Bunting",
        corbun1:"Corn Bunting",
        chebun2:"Chestnut-eared Bunting",
        rocbun1:"Rock Bunting",
        meabun1:"Meadow Bunting",
        cirbun1:"Cirl Bunting",
        yellow2:"Yellowhammer",
        pinbun:"Pine Bunting",
        ortbun1:"Ortolan Bunting",
        crebun2:"Cretzschmar's Bunting",
        reebun:"Reed Bunting",
        yebbun:"Yellow-breasted Bunting",
        litbun:"Little Bunting",
        rusbun:"Rustic Bunting",
        blfbun1:"Black-faced Bunting",
        chebun1:"Chestnut Bunting",
        yebbun1:"Yellow-browed Bunting",
        larspa:"Lark Sparrow",
        daejun:"Dark-eyed Junco",
        whcspa:"White-crowned Sparrow",
        whtspa:"White-throated Sparrow",
        savspa:"Savannah Sparrow",
        sonspa:"Song Sparrow",
        yehbla:"Yellow-headed Blackbird",
        boboli:"Bobolink",
        balori:"Baltimore Oriole",
        rewbla:"Red-winged Blackbird",
        bnhcow:"Brown-headed Cowbird",
        ovenbi1:"Ovenbird",
        norwat:"Northern Waterthrush",
        gowwar:"Golden-winged Warbler",
        bawwar:"Black-and-white Warbler",
        tenwar:"Tennessee Warbler",
        comyel:"Common Yellowthroat",
        amered:"American Redstart",
        camwar:"Cape May Warbler",
        norpar:"Northern Parula",
        magwar:"Magnolia Warbler",
        bkbwar:"Blackburnian Warbler",
        yelwar:"Yellow Warbler",
        bkpwar:"Blackpoll Warbler",
        yerwar:"Yellow-rumped Warbler",
        wlswar:"Wilson's Warbler",
        scatan:"Scarlet Tanager",
        robgro:"Rose-breasted Grosbeak",
        indbun:"Indigo Bunting",
        paibun:"Painted Bunting"
}

export default britBirds;